[build]
builder = "NIXPACKS"
buildCommand = "npm install && npx turbo build --filter=server"

[deploy]
startCommand = "node apps/server/dist/index.mjs"
healthcheckPath = "/"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
